version: "3.8"
services:
  mysql:
    image: mysql:5.7
    networks:
      - mysqlnet
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  blog:
    build: .
    networks:
      - mysqlnet
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DB_CONNECTION: "mysql+pymysql://root:123456@mysql/blog?charset=utf8"
      FLASK_ENV: development
networks:
  mysqlnet:
volumes:
  mysql:
  mysql_config: