version: '3'

services:
  frontend:
    image: "nginx:1.21-alpine"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8111:8111
    depends_on:
      - flaskapp

  flaskapp:
    build: .
    environment:
      - PORT=5000
      - DB_CONNECTION=mysql+pymysql://root:passW0rd@mysql/blog?charset=utf8
    depends_on:
      - mysql

  mysql:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=passW0rd
      - MYSQL_DATABASE=blog